language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
    - nelsonlz@outlook.com
script:
# Unit Test & Integration Test
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
# Calidad codigo: Sonarcloud
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nelson-lpz-soft -Dsonar.login=$SONAR
#Deploy https://ecosystem-nlp.heroku.com/api
#deploy:
#  provider: heroku
#  api_key: $HEROKU
#  on:
#    branch: master
#  app: patronesGoF #, por defecto, nombre del artefacto en caso de que el nombre este ocupado
